# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SkillShareHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkillShareHub
     pod 'CometChatPro', '3.0.918'
     pod 'CometChatCalls', '3.0.2'
     pod 'CometChatUIKitSwift','4.2.1'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseAnalytics'

end
